# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5724f8bf3bf0cf6ae78c111688cd42b08173d609bcffdb0de9e2de67ea392347c3bce3fe10965856757b73201f3c630e6659f2e044dbaa53d2e433fc1559fda3

test:
  secret_key_base: deb2ab89c23ca3cbf37e6120f9d6500db404c511ed38203343c341e1b087d849b2cb0f606f667bb40df6bff8cf271b8747847bb7d9e10cd0c1cbed1b8e80d2cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
